version: '3.8'

services:
    doc_hunter_service:
        build:
            context: ./doc_hunter_service
        image: doc-hunter-service
        container_name: doc-hunter-service
        restart: unless-stopped
        ports:
            - "8000:8000"
        command: gunicorn --workers=3 -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker doc_hunter_service:api

    redis:
        image: redis
        container_name: redis
        hostname: redis
        restart: unless-stopped
        volumes:
            - ./redis/data:/data
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        expose:
            - 6379
        command: redis-server /usr/local/etc/redis/redis.conf
